name: ChatPlugin
main: me.remigio07_.chatplugin.Main$Spigot$MainSpigot
version: '∞'
api-version: 1.13
author: Remigio07_
website: https://megaproserver.com/chatplugin
description: 'A lightweight yet complete plugin which handles just too many features! Check the website for info: https://megaproserver.com/ChatPlugin'
softdepend: [Essentials, ViaVersion, ProtocolSupport, Rewards, Vault, PlaceholderAPI, MVdWPlaceholderAPI, CombatLogX, GadgetsMenu, PlayerParticles, Matrix, Vulcan]
commands:
  chatplugin:
    description: ChatPlugin's main command.
    usage: /chatplugin help
    aliases: [chatpl, chatp, chat, cplugin, cp]
  ping:
    description: Ping command.
    usage: /ping [player]
    aliases: [pong]
  scoreboard:
    description: Scoreboard command.
    usage: /scoreboard
    aliases: [scrboard, scoreb, sboard, sb]
  vanish:
    description: Vanish command.
    usage: /vanish [player]
    aliases: [v, hide, fade]
  clearchat:
    description: Clear chat command.
    usage: /clearchat
    aliases: [clrchat, cchat]
  mute:
    description: Mute command.
    usage: /mute <player> <time> [reason] [-s] [-t]
    aliases: [tempmute, shut, tshut, tmute]
  permanentmute:
    description: Permanent mute command.
    usage: /permanentmute <player> [reason] [-s] [-t]
    aliases: [permmute, permamute, pmute, permshut, permashut, pshut]
  unmute:
    description: Unmute command.
    usage: /unmute <player>
    aliases: [umute, untempmute, unshut, utmute]
  mutelist:
    description: Mute list command.
    usage: /mutelist [refresh|next|previous|ids]
    aliases: [mlist, mutel, shutlist, ml, mutes]
  muteall:
    description: Muteall command.
    usage: /muteall
    aliases: [mutea, mall, disablechat, enablechat]
  kick:
    description: Kick command.
    usage: /kick <player> [reason] [-s]
    aliases: [k]
  ban:
    description: Ban command.
    usage: /ban <player> [reason] [-s] [-t]
    aliases: [permanentban, permaban, permban, pban]
  tempban:
    description: Tempban command.
    usage: /tempban <player> <time> [reason] [-s] [-t]
    aliases: [tmpban, tban]
  banip:
    description: Ban IP command.
    usage: /banip <player|IP address> [reason] [-s] [-t]
    aliases: [ban-ip, bip, banaddress, baddress, banadd]
  tempbanip:
    description: Tempban IP command.
    usage: /tempbanip <player|IP address> <time> [reason] [-s] [-t]
    aliases: [tempban-ip, tempbip, tempbanaddress, tempbaddress, tempbanadd, tbip, tbanip]
  unban:
    description: Unban command.
    usage: /unban <player>
    aliases: [pardon, uban]
  unbanip:
    description: Unban IP command.
    usage: /unbanip <player>
    aliases: [pardonip, pardon-ip, ubanip, uban-ip]
  baninfo:
    description: Ban info command.
    usage: /baninfo <ID>
    aliases: [binfo, checkban, cban, banipinfo, bipinfo, checkbanip, cbanip, ban-ipinfo, b-ipinfo, checkban-ip]
  banlist:
    description: Ban list command.
    usage: /banlist [refresh|next|previous|ids]
    aliases: [blist, banl, bl, bans]
  addbanwaveentry:
    description: Add banwave entry command.
    usage: /addbanwaveentry <player|IP address> <time> [reason] [-s] [-t]
    aliases: [addbwentry, newbanwaveentry, newbwentry]
  removebanwaveentry:
    description: Remove banwave entry command.
    usage: /removebanwaveentry <player|IP address>
    aliases: [removebwentry]
  warning:
    description: Warning command.
    usage: /warning <player> [reason] [-s] [-t]
    aliases: [warn]
  removewarning:
    description: Remove warning command.
    usage: /removewarning <player>
    aliases: [removewarn, rmwarning, rmwarn, rmw, unwarning, unwarn]
  clearwarnings:
    description: Clear warnings command.
    usage: /clearwarnings <player>
    aliases: [clearwarning, clearwarns, clearwarn, cwarwnings, clearw]
  warninginfo:
    description: Warning info command.
    usage: /warninginfo <id>
    aliases: [warninfo, winfo, checkwarning, checkwarn, cwarning, cwarn]
  warnlist:
    description: Warn list command.
    usage: /warnlist [refresh|next|previous|ids]
    aliases: [warningslist, warninglist, warnslist, wlist, wl, warnings, warns]
  broadcast:
    description: Broadcast command.
    usage: /broadcast <message>
    aliases: [bcast, shout, local, bc]
  broadcastraw:
    description: Broadcast raw command.
    usage: /broadcastraw <message>
    aliases: [bcastraw, bcastr, shoutraw, localraw, bcraw, bcr]
  globalbroadcast:
    description: Global broadcast command.
    usage: /globalbroadcast <message>
    aliases: [gbcast, gshout, global, gbc]
  fakejoin:
    description: Fake join command.
    usage: /fakejoin
    aliases: [fjoin, fakej]
  fakequit:
    description: Fake quit command.
    usage: /fakequit
    aliases: [fquit, fakeq]
  fakekick:
    description: Fake kick command.
    usage: /fakekick <player> [-c]
    aliases: [fkick, fakek, fakecrash, fcrash, fakec]
  rankinfo:
    description: Rank info command.
    usage: /rankinfo <player>
    aliases: [rinfo, rank]
  staffchat:
    description: Staff chat command.
    usage: /staffchat [message]
    aliases: [staffc, schat, sch, sc]
  playerinfo:
    description: Player info command.
    usage: /playerinfo <player>
    aliases: [playeri, plinfo, pinfo, whois, pi]
  iplookup:
    description: IP lookup command.
    usage: /iplookup <player|IP address>
    aliases: [lookup, geolocalize, geolocate, geol, iplook, ipl]
  lastseen:
    description: Last seen comamnd.
    usage: /lastseen <player>
    aliases: [seen, last, lastlogout, lastlogin]
  muteinfo:
    description: Mute info command.
    usage: /muteinfo <ID>
    aliases: [minfo, checkmute, cmute]
  kickinfo:
    description: Kick info command.
    usage: /kickinfo <ID>
    aliases: [kinfo, checkkick, ckick]
  silentjoin:
    description: Silent join command.
    usage: /silentjoin <server>
    aliases: [sjoin, silentj, sj]
  tps:
    description: TPS command.
    usage: /tps
    aliases: [tickspersecond, ticks, tick, lag]
  violations:
    description: Violations command.
    usage: /violations [refresh|next|previous]
    aliases: [violation, viol, vl]
  language:
    description: Language command.
    usage: /language
    aliases: [languages, lang, langs, localization, locale, l18n]
  playerpunishments:
    description: Player punishments command.
    usage: /playerpunishments <player> [refresh|next|previous|ids]
    aliases: [playerpunishment, ppunishments, punishments, punishment, punishmentslist, punishlist]
  playerviolations:
    description: Player violations command.
    usage: /playerviolations <player> [refresh|next|previous]
    aliases: [playerviolation, pviolations, playerviols, playerviol, pviols, pviol, pvls, pvl]
