name: ChatPlugin
main: me.remigio07.chatplugin.bootstrap.BukkitBootstrapper
version: '${version}'
api-version: '1.13'
author: Remigio07
website: https://remigio07.me/chatplugin
description: 'A feature-rich and modular chat ecosystem, lightweight and efficient by design.'
softdepend: [CombatLogX, DiscordSRV, Essentials, floodgate, GadgetsMenu, Geyser-Spigot, LuckPerms, Matrix, MVdWPlaceholderAPI, Negativity, PlaceholderAPI, PlayerParticles, ProtocolSupport, UltraCosmetics, Vault, ViaVersion, Vulcan, WorldGuard]
