name: ChatPlugin
main: me.remigio07.chatplugin.bootstrap.BukkitBootstrapper
version: '${version}'
api-version: '1.13'
author: Remigio07
website: https://remigio07.me/chatplugin
description: 'A lightweight yet complete plugin which handles just too many features!'
softdepend: [CombatLogX, DiscordSRV, Essentials, floodgate, GadgetsMenu, Geyser-Spigot, LuckPerms, Matrix, MVdWPlaceholderAPI, Negativity, PlaceholderAPI, PlayerParticles, ProtocolSupport, UltraCosmetics, Vault, ViaVersion, Vulcan, WorldGuard]
